[monorepo]
name = "engine"
display_name = "GE Engine"
git = "git@github.com:GrandEngineering/engine.git"

[[repo]]
name = "engineweb"
display_name = "GE Engine Website"
git = "git@github.com:IGN-Styly/engineweb.git"
path = "engineweb"
test = "npm run lint"

[[repo]]
path = "enginelib"
name = "enginelib"
display_name = "GE EngineLib"
git = "git@github.com:GrandEngineering/enginelib.git"
build = "cargo build"
test = "cargo test"

[[repo]]
name = "engine_core"
display_name = "GE Engine Core"
external = false
path = "engine_core"
build = "cargo build"

[[repo]]
name = "engine"
external = false
path = "engine"
test = "cargo test"
