[monorepo]
name = "engine"
git = "git@github.com:GrandEngineering/engine.git"
run = "cargo build && cargo run --bin server --features dev"
opt_run = "cargo build --release && cargo run --bin server --release"
build = "cargo build"
opt_build = "cargo build --release"
[[monorepo.libs]]
name = "enginelib"
build = "cargo build"
opt_build = "cargo build --release"
[[monorepo.libs]]
name = "engine_core"
build = "cargo build"
opt_build = "cargo build --release"

[[monorepo.bins]]
name = "server --features dev"
build = "cargo build --features dev"
opt_build = "cargo build --release --features dev"
run = "cargo run --bin server --features dev"
opt_run = "cargo run --bin server --release --features dev"
[[monorepo.bins]]
name = "client"
build = "cargo build"
opt_build = "cargo build --release --features dev"
run = "cargo run --bin client --features dev"
opt_run = "cargo run --bin client --release --features dev"
[[monorepo.macros]]
name = "fmt"
run = "cargo fmt --all"
