[package]
name = "enginelib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
fern = "0.7.0"
humantime = "2.1.0"
log = "0.4.22"
