[package]
name = "enginelib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
directories = "5.0.1"
libloading = "0.8.6"
oxifs = "0.1.0"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.18"
[build-dependencies]
vergen-gix = { version = "1.0.0", features = ["build", "cargo", "rustc"] }
