[module]
mod_id = "engine_core"
mod_author = "styly"
mod_name = "engine_core"
mod_version = "0.1"
mod_description = "A brief description."
mod_license = "ARR"
mod_credits = "Contributors"
mod_display_url = ""
mod_issue_tracker = ""
engine_repo = "https://github.com/GrandEngineering/engine.git"
engine_commit = "abe9669ee4980c2087870ffbb8d5fcc31f0d8866"

# [[dependencies]]
# git_repo = ""
# git_commit = ""
# mod_id = ""
